apiVersion: batch/v1
kind: Job
metadata:
  name: argo-kubectl-vcluster
spec:
  template:
    spec:
      containers:
      - name: argo-kubectl-vcluster
        command: ["/script/vcluster-create.sh"]
        args:
        - tejatest@gmail.com
        env:
        - name: argocdhost
          value: feb20limits.argo.ninja-test.opsmx.org
        image: quay.io/opsmxpublic/argo-kubectl-vcluster:v1
        volumeMounts:
        - mountPath: /kube
          name: kubeconfig
        - mountPath: /argocd
          name: argocd
        - mountPath: /init
          name: init
        - mountPath: /values
          name: values
        - mountPath: /script
          name: script
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig
      - name: argocd
        secret:
          secretName: argocd-initial-admin-secret
      - name: init
        configMap:
          name: init-vcluster
          items:
          - key: "init-vcluster.yaml"
            path: "init-vcluster.yaml"
      - name: values
        configMap:
          name: vcluster-values-yaml
          items:
          - key: "values.yaml"
            path: "values.yaml"
      - name: script
        configMap:
          name: vcluster-create-script
          defaultMode: 0744
          items:
          - key: "vcluster-create.sh"
            path: "vcluster-create.sh"
      restartPolicy: Never
  backoffLimit: 4
